import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import {getFirestore,collection,doc,onSnapshot,runTransaction,serverTimestamp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
const firebaseConfig={apiKey:'AIzaSyBXewhDeLaoQ8-cdkNOKBRaZoW9L05tWR8',authDomain:'frota-carrinhos.firebaseapp.com',projectId:'frota-carrinhos',storageBucket:'frota-carrinhos.firebasestorage.app',messagingSenderId:'877603189752',appId:'1:877603189752:web:7de50f766da63d8906dc0d',measurementId:'G-PER0L9QER7'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),brl=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),dateKey=t=>{const d=new Date(t);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const initial=['Drift Branco','Drift Verde','Drift Céu 01','Drift Céu 02','Carrinho Vermelho','Kart Vermelho','Quadriciclo Branco','Jeep 4x4','Kart Rosa'];
let items=[],history=[],unsubs=[],ready={items:false,history:false},selected=null,mode='start',audio=null,soundOn=false,busy=false,notified=new Set();
const eq=id=>doc(db,'equipamentos',id),rental=id=>doc(db,'locacoes',id),now=()=>Date.now();
function info(s){$('notice').textContent=s}function left(x){return x.endAt==null?x.remaining||0:Math.max(0,Math.ceil((x.endAt-now())/1000))}function status(x){return x.endAt!=null?(left(x)?'running':'expired'):(x.remaining>0?'paused':'free')}
function fmt(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function beep(){if(!soundOn||!audio)return;try{audio.resume();let t=audio.currentTime;for(let i=0;i<3;i++){const o=audio.createOscillator(),g=audio.createGain();o.type='square';o.frequency.value=880;o.connect(g);g.connect(audio.destination);g.gain.setValueAtTime(.0001,t+i*.38);g.gain.exponentialRampToValueAtTime(.15,t+i*.38+.02);g.gain.exponentialRampToValueAtTime(.0001,t+i*.38+.25);o.start(t+i*.38);o.stop(t+i*.38+.27)}}catch{}}
function totals(){ $('active').textContent=items.filter(x=>status(x)==='running').length;$('ended').textContent=items.filter(x=>status(x)==='expired').length;$('free').textContent=items.filter(x=>status(x)==='free').length;const today=dateKey(now());$('today').textContent=brl(history.flatMap(h=>h.charges||[]).filter(c=>dateKey(c.at)===today).reduce((a,c)=>a+Number(c.amount||0),0))}
function render(){const labels={running:'Em uso',expired:'TEMPO ENCERRADO',paused:'Pausado',free:'Disponível'};$('grid').innerHTML=items.map(x=>{const s=status(x);return `<article class="card ${s}" data-id="${esc(x.id)}"><div class="top"><h2>${esc(x.name)}</h2><span class="badge">${labels[s]}</span></div><div class="clock" id="clock-${esc(x.id)}">${fmt(left(x))}</div><div class="meta">${x.customer?'Cliente: '+esc(x.customer):'&nbsp;'}</div><div class="actions"><button class="primary" data-act="start">${s==='free'?'▶ Iniciar':'↻ Nova locação'}</button><button data-act="pause" ${s==='free'||s==='expired'?'disabled':''}>${s==='paused'?'▶ Retomar':'Ⅱ Pausar'}</button><button class="warn" data-act="extra" ${s==='free'?'disabled':''}>＋ Tempo</button><button class="danger wide" data-act="reset" ${s==='free'?'disabled':''}>✓ Encerrar / liberar carrinho</button></div></article>`}).join('');totals()}
function tick(){for(const x of items){if(status(x)==='expired'&&!notified.has(x.id+':'+x.endAt)){notified.add(x.id+':'+x.endAt);beep();navigator.vibrate?.([200,100,200]);info('⏰ Tempo encerrado: '+x.name)}const el=$('clock-'+x.id);if(el)el.textContent=fmt(left(x))}totals()}
function report(){let old=$('equipmentFilter').value;const opts=[...new Map([...items,...history.map(h=>({id:h.equipmentId,name:h.equipment}))].map(x=>[x.id,x.name])).entries()];$('equipmentFilter').innerHTML='<option value="">Todos</option>'+opts.map(([id,n])=>`<option value="${esc(id)}">${esc(n)}</option>`).join('');$('equipmentFilter').value=old;const from=$('from').value,to=$('to').value,equip=$('equipmentFilter').value;const rows=history.flatMap(h=>(h.charges||[]).filter(c=>(!from||dateKey(c.at)>=from)&&(!to||dateKey(c.at)<=to)&&(!equip||h.equipmentId===equip)).map(c=>({h,c})));$('revenue').textContent=brl(rows.reduce((a,r)=>a+Number(r.c.amount||0),0));$('count').textContent=new Set(rows.map(r=>r.h.id)).size;for(const [id,p] of [['pix','Pix'],['cash','Dinheiro'],['card','Cartão'],['other','Outros']])$(id).textContent=brl(rows.filter(r=>r.c.payment===p).reduce((a,r)=>a+Number(r.c.amount||0),0));const group=new Map();for(const {h,c} of rows){let g=group.get(h.equipmentId)||{name:h.equipment,total:0,ids:new Set()};g.total+=Number(c.amount||0);g.ids.add(h.id);group.set(h.equipmentId,g)}$('byEquipment').innerHTML=[...group.values()].sort((a,b)=>b.total-a.total).map(g=>`<tr><td>${esc(g.name)}</td><td>${g.ids.size}</td><td class="money">${brl(g.total)}</td></tr>`).join('')||'<tr><td colspan="3">Nenhuma cobrança no período.</td></tr>';const filtered=history.filter(h=>(!from||dateKey(h.startedAt)>=from)&&(!to||dateKey(h.startedAt)<=to)&&(!equip||h.equipmentId===equip)).sort((a,b)=>b.startedAt-a.startedAt);$('historyRows').innerHTML=filtered.map(h=>`<tr><td>${new Date(h.startedAt).toLocaleString('pt-BR')}</td><td>${esc(h.equipment)}<br><span class="muted">${esc(h.customer)}</span></td><td>${h.minutes}</td><td class="money">${brl((h.charges||[]).reduce((a,c)=>a+Number(c.amount||0),0))}</td><td>${esc([...new Set((h.charges||[]).map(c=>c.payment))].join(', '))}</td><td>${h.finishedAt?'Encerrada':'Em andamento'}</td><td>${h.finishedAt?new Date(h.finishedAt).toLocaleString('pt-BR'):'—'}</td></tr>`).join('')||'<tr><td colspan="7">Nenhuma locação no período.</td></tr>';return {rows,filtered}}
function csv(filename,rows){const cell=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function ask(x,kind){selected=x.id;mode=kind;$('startTitle').textContent=(kind==='extra'?'Adicionar tempo — ':'Iniciar locação — ')+x.name;$('minutes').value=kind==='extra'?5:10;$('customerGroup').classList.toggle('hidden',kind==='extra');$('customer').value=kind==='extra'?x.customer:'';$('amount').value=kind==='extra'?'5.00':'10.00';$('payment').value='Pix';$('confirmStart').textContent=kind==='extra'?'Adicionar':'Iniciar';$('startDialog').showModal()}
async function change(action,id,values={}){if(busy)return;busy=true;try{await runTransaction(db,async tx=>{const ref=eq(id),snap=await tx.get(ref);if(!snap.exists())throw Error('Carrinho não encontrado.');const x=snap.data(),s=status(x),t=now(),rid=x.rentalId,oldRef=rid?rental(rid):null;let old=null;if(oldRef){const oldSnap=await tx.get(oldRef);old=oldSnap.exists()?oldSnap.data():null}if(action==='start'){if(s!=='free'&&!values.replace)throw Error('Carrinho ocupado. Atualize a página.');if(old&& !old.finishedAt)tx.update(oldRef,{finishedAt:t,finishReason:'Substituída por nova locação'});const newRef=doc(collection(db,'locacoes'));const h={equipmentId:id,equipment:x.name,customer:values.customer,startedAt:t,finishedAt:null,minutes:values.mins,charges:[{at:t,amount:values.amount,payment:values.payment}],operator:auth.currentUser.email};tx.set(newRef,h);tx.update(ref,{endAt:t+values.mins*60000,remaining:0,customer:values.customer,rentalId:newRef.id,updatedAt:serverTimestamp()})}else if(action==='extra'){if(s==='free'||!old||old.finishedAt)throw Error('Locação não está ativa.');tx.update(oldRef,{minutes:(old.minutes||0)+values.mins,charges:[...(old.charges||[]),{at:t,amount:values.amount,payment:values.payment}]});tx.update(ref,{endAt:t+(left(x)+values.mins*60000),remaining:0,updatedAt:serverTimestamp()})}else if(action==='pause'){if(s==='free'||s==='expired')throw Error('Carrinho não está em uso.');tx.update(ref,s==='paused'?{endAt:t+x.remaining*1000,remaining:0,updatedAt:serverTimestamp()}:{endAt:null,remaining:left(x),updatedAt:serverTimestamp()})}else if(action==='reset'){if(s==='free')throw Error('Carrinho já está disponível.');if(old&&!old.finishedAt)tx.update(oldRef,{finishedAt:t,finishReason:'Encerrada pelo operador'});tx.update(ref,{endAt:null,remaining:0,customer:'',rentalId:null,updatedAt:serverTimestamp()})}});info('✅ Operação salva e sincronizada.')}catch(e){console.error(e);info('⚠️ '+(e.message||'Não foi possível salvar.'));alert('Operação não salva: '+e.message)}finally{busy=false}}
$('grid').addEventListener('click',e=>{const b=e.target.closest('button[data-act]');if(!b)return;const x=items.find(i=>i.id===b.closest('.card').dataset.id);if(!x)return;const a=b.dataset.act;if(a==='start'){const replace=status(x)!=='free';if(replace&&!confirm('Encerrar a locação atual e iniciar outra em '+x.name+'?'))return;ask(x,'start');$('startDialog').dataset.replace=String(replace)}else if(a==='extra')ask(x,'extra');else if(a==='pause')change('pause',x.id);else if(a==='reset'&&confirm('Encerrar e liberar '+x.name+'?'))change('reset',x.id)});
$('startForm').addEventListener('submit',e=>{if(e.submitter?.value!=='ok')return;const mins=Number($('minutes').value),amount=Number($('amount').value);if(!Number.isInteger(mins)||mins<1||mins>600||!Number.isFinite(amount)||amount<0||amount>100000){e.preventDefault();alert('Confira os minutos e o valor.')}});
$('startDialog').addEventListener('close',()=>{if($('startDialog').returnValue!=='ok')return;const mins=Number($('minutes').value),amount=Number($('amount').value);if(!Number.isInteger(mins)||mins<1||mins>600||!Number.isFinite(amount)||amount<0||amount>100000)return;change(mode,selected,{mins,amount:Math.round(amount*100)/100,payment:$('payment').value,customer:$('customer').value.trim(),replace:$('startDialog').dataset.replace==='true'})});
$('add').onclick=()=>$('addDialog').showModal();$('addDialog').addEventListener('close',async()=>{if($('addDialog').returnValue!=='ok')return;const name=$('newName').value.trim();if(!name)return;try{await runTransaction(db,async tx=>{const ref=doc(collection(db,'equipamentos'));tx.set(ref,{name,endAt:null,remaining:0,customer:'',rentalId:null,createdAt:serverTimestamp()})});$('newName').value=''}catch(e){info('⚠️ '+e.message)}});
$('sound').onclick=async()=>{try{audio??=new(window.AudioContext||window.webkitAudioContext)();await audio.resume();soundOn=true;$('sound').textContent='🔔 Som ativado';beep()}catch{info('O navegador bloqueou o áudio.')}};$('test').onclick=()=>soundOn?beep():info('Primeiro ative o som.');
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));['central','financeiro','historico'].forEach(id=>$(id).classList.toggle('hidden',id!==b.dataset.tab));report()});['from','to','equipmentFilter'].forEach(id=>$(id).addEventListener('change',report));$('from').value=dateKey(now());$('to').value=dateKey(now());$('export').onclick=()=>csv('faturamento-'+dateKey(now())+'.csv',[['Data','Equipamento','Cliente','ID','Valor','Pagamento'],...report().rows.map(({h,c})=>[new Date(c.at).toLocaleString('pt-BR'),h.equipment,h.customer,h.id,Number(c.amount).toFixed(2).replace('.',','),c.payment])]);$('exportHistory').onclick=()=>csv('historico-'+dateKey(now())+'.csv',[['Início','Fim','Equipamento','Cliente','Minutos','Valor','Pagamentos','Situação','ID'],...report().filtered.map(h=>[new Date(h.startedAt).toLocaleString('pt-BR'),h.finishedAt?new Date(h.finishedAt).toLocaleString('pt-BR'):'',h.equipment,h.customer,h.minutes,(h.charges||[]).reduce((a,c)=>a+Number(c.amount||0),0).toFixed(2).replace('.',','),(h.charges||[]).map(c=>c.payment).join(', '),h.finishedAt?'Encerrada':'Em andamento',h.id])]);
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='Entrando...';try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);$('password').value=''}catch(e){$('loginError').textContent='Não foi possível entrar. Confira e-mail e senha.'}});$('logout').onclick=()=>signOut(auth);
$('initialize').onclick=async()=>{if(items.length||!confirm('Cadastrar os nove carrinhos iniciais?'))return;try{await runTransaction(db,async tx=>{const refs=initial.map((_,i)=>eq('inicial-'+String(i+1).padStart(2,'0')));const snaps=await Promise.all(refs.map(ref=>tx.get(ref)));refs.forEach((ref,i)=>{if(!snaps[i].exists())tx.set(ref,{name:initial[i],endAt:null,remaining:0,customer:'',rentalId:null,createdAt:serverTimestamp()})})});info('Carrinhos cadastrados.')}catch(e){info('⚠️ '+e.message)}};
onAuthStateChanged(auth,user=>{unsubs.forEach(fn=>fn());unsubs=[];items=[];history=[];ready={items:false,history:false};$('loginScreen').classList.toggle('hidden',!!user);$('appScreen').classList.toggle('hidden',!user);if(!user)return;$('operator').textContent=user.email;info('Conectando ao banco de dados...');unsubs.push(onSnapshot(collection(db,'equipamentos'),snap=>{items=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));ready.items=true;$('initialize').classList.toggle('hidden',items.length>0);render();report();if(ready.history)info('☁️ Conectado: dados sincronizados entre os operadores.')},e=>info('⚠️ Falha ao ler carrinhos: '+e.message)));unsubs.push(onSnapshot(collection(db,'locacoes'),snap=>{history=snap.docs.map(d=>({id:d.id,...d.data()}));ready.history=true;render();report();if(ready.items)info('☁️ Conectado: dados sincronizados entre os operadores.')},e=>info('⚠️ Falha ao ler faturamento: '+e.message)))});
setInterval(tick,500);document.addEventListener('visibilitychange',()=>{if(!document.hidden){tick();render()}});
